apiVersion: v1
kind: Secret
metadata:
  name: hindsight_agent-secrets
  namespace: incident-agent-system
type: Opaque
stringData:
  jwt-secret: "hindsight_agent_super_secret_enterprise_key_2026"
  postgres-password: "incident_agent_secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: hindsight_agent-secrets
  namespace: hindsight-agent-apps
type: Opaque
stringData:
  jwt-secret: "hindsight_agent_super_secret_enterprise_key_2026"
  postgres-password: "incident_agent_secret"
