apiVersion: v1
data:
  ENVIRONMENT: production
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.incident-agent-observability.svc.cluster.local:4317
  POSTGRES_DB: incident_agent_db
  POSTGRES_HOST: postgres-db.incident-agent-system.svc.cluster.local
  POSTGRES_PORT: '5432'
  REDIS_HOST: redis-master.incident-agent-system.svc.cluster.local
  REDIS_PORT: '6379'
kind: ConfigMap
metadata:
  name: hindsight-agent-global-config
  namespace: incident-agent-system
---
apiVersion: v1
data:
  ENVIRONMENT: production
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.incident-agent-observability.svc.cluster.local:4317
  POSTGRES_DB: incident_agent_db
  POSTGRES_HOST: postgres-db.incident-agent-system.svc.cluster.local
  POSTGRES_PORT: '5432'
  REDIS_HOST: redis-master.incident-agent-system.svc.cluster.local
  REDIS_PORT: '6379'
kind: ConfigMap
metadata:
  name: hindsight-agent-global-config
  namespace: hindsight-agent-apps
