"""
====================================================================
agent/llm_client.py - Unified LLM Client
====================================================================
Purpose: Wrapper client that routes model requests to AWS Bedrock,
         OpenAI, or Anthropic Claude direct API.
         It supports explicit keys configured via config/config.yaml.
====================================================================
"""

import json
import logging
import requests
import boto3
from typing import Any, Dict, Optional

from shared.config import config

# ---- Logging Setup ----
logger = logging.getLogger(__name__)


class UnifiedLLMClient:
    """
    Unified LLM Client that abstracts over different provider APIs.
    Loads connection parameters from the centralized YAML configuration.
    """

    def __init__(self, provider: Optional[str] = None):
        """
        Initialize the unified client with a target provider.
        
        Args:
            provider: 'bedrock', 'openai', or 'anthropic' (defaults to config)
        """
        self.provider = provider or config.default_llm_provider
        self.provider = self.provider.lower()
        logger.info(f"UnifiedLLMClient initialized with provider: {self.provider}")

    def invoke(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: int = 4096,
        temperature: float = 0.1,
    ) -> Optional[str]:
        """
        Invoke the configured LLM API.
        
        Args:
            prompt: The user query / prompt text
            system_prompt: Optional instructions for the model's system role
            max_tokens: Maximum tokens in the generated response
            temperature: Sampling temperature (0.0=deterministic, 1.0=creative)
            
        Returns:
            The text content generated by the model, or None if failed
        """
        # Build prioritized provider fallback list
        candidate_providers = [self.provider]
        for p in ["openai", "anthropic", "bedrock"]:
            if p not in candidate_providers:
                candidate_providers.append(p)

        last_error = None
        for prov in candidate_providers:
            try:
                res = None
                if prov == "bedrock":
                    res = self._invoke_bedrock(prompt, system_prompt, max_tokens, temperature)
                elif prov == "openai":
                    res = self._invoke_openai(prompt, system_prompt, max_tokens, temperature)
                elif prov == "anthropic":
                    res = self._invoke_anthropic(prompt, system_prompt, max_tokens, temperature)
                
                # Verify that response is valid and not an error string
                if res and not (isinstance(res, str) and res.startswith("[Error")):
                    return res
                else:
                    logger.warning(f"Provider {prov} returned error/empty: {res}. Switching to next provider...")
            except Exception as e:
                logger.warning(f"Provider {prov} failed with exception: {e}. Switching to next provider...")
                last_error = e

        logger.error(f"All configured LLM providers failed: {last_error}")
        return None

    def _invoke_bedrock(
        self,
        prompt: str,
        system_prompt: Optional[str],
        max_tokens: int,
        temperature: float,
    ) -> Optional[str]:
        """Invoke AWS Bedrock Runtime client."""
        from lambda_.ai.bedrock_client import BedrockLLMClient
        
        client = BedrockLLMClient()
        
        # Override the boto3 bedrock client if custom credentials are set in config.yaml
        if config.aws.aws_access_key_id and config.aws.aws_secret_access_key:
            logger.info("Initializing Bedrock runtime client with explicit AWS keys from config.yaml")
            client.client = boto3.client(
                service_name="bedrock-runtime",
                region_name=config.aws.region,
                aws_access_key_id=config.aws.aws_access_key_id,
                aws_secret_access_key=config.aws.aws_secret_access_key,
                aws_session_token=config.aws.aws_session_token or None
            )
            
        return client.invoke(
            prompt=prompt,
            system_prompt=system_prompt,
            max_tokens=max_tokens,
            temperature=temperature
        )

    def _invoke_openai(
        self,
        prompt: str,
        system_prompt: Optional[str],
        max_tokens: int,
        temperature: float,
    ) -> Optional[str]:
        """Invoke OpenAI API via lightweight requests HTTP call."""
        api_key = config.openai.api_key
        model_id = config.openai.model_id
        api_base = config.openai.api_base

        if not api_key:
            logger.error("OpenAI API key is missing. Configure it in config/config.yaml.")
            return "[Error: OpenAI API key is missing]"

        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}"
        }

        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        data = {
            "model": model_id,
            "messages": messages,
            "max_tokens": max_tokens,
            "temperature": temperature
        }

        url = f"{api_base.rstrip('/')}/chat/completions"
        logger.info(f"Invoking OpenAI API direct request: model={model_id}")

        try:
            response = requests.post(url, headers=headers, json=data, timeout=90)
            response.raise_for_status()
            res_json = response.json()
            return res_json["choices"][0]["message"]["content"]
        except Exception as e:
            logger.error(f"OpenAI API call failed: {e}")
            if hasattr(e, 'response') and e.response is not None:
                logger.error(f"Response body: {e.response.text}")
            return f"[Error calling OpenAI API: {e}]"

    def _invoke_anthropic(
        self,
        prompt: str,
        system_prompt: Optional[str],
        max_tokens: int,
        temperature: float,
    ) -> Optional[str]:
        """Invoke Anthropic Claude API directly via requests HTTP call."""
        api_key = config.anthropic.api_key
        model_id = config.anthropic.model_id

        if not api_key:
            logger.error("Anthropic API key is missing. Configure it in config/config.yaml.")
            return "[Error: Anthropic API key is missing]"

        headers = {
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01"
        }

        messages = [{"role": "user", "content": prompt}]

        data = {
            "model": model_id,
            "messages": messages,
            "max_tokens": max_tokens,
            "temperature": temperature
        }
        if system_prompt:
            data["system"] = system_prompt

        url = "https://api.anthropic.com/v1/messages"
        logger.info(f"Invoking Anthropic API direct request: model={model_id}")

        try:
            response = requests.post(url, headers=headers, json=data, timeout=90)
            response.raise_for_status()
            res_json = response.json()
            return res_json["content"][0]["text"]
        except Exception as e:
            logger.error(f"Anthropic API call failed: {e}")
            if hasattr(e, 'response') and e.response is not None:
                logger.error(f"Response body: {e.response.text}")
            return f"[Error calling Anthropic API: {e}]"
